/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package flores.app;

import com.toedter.calendar.JCalendar;
import flores.utils.FechasUtils;
import java.awt.Window;
import java.util.GregorianCalendar;
import javax.swing.SwingUtilities;

/**
 *
 * @author vPalomo
 */
public class FechaEntrega extends javax.swing.JPanel {
    private GregorianCalendar fechaSel=new GregorianCalendar();
    private String fechaSelString;
    private JCalendar calendar;
    private String opcion;
    public static final String ACEPTAR="aceptar";
    public static final String CANCELAR="cancelar";
    /**
     * Creates new form FechaEntrega
     */
    public FechaEntrega() {
        initComponents();
        opcion=FechaEntrega.CANCELAR;
 
        // Instanciar Componente
        calendar = new JCalendar();

        // Ubicar y agregar al panel
        calendar.setBounds(25, 40, 180, 180);
        calendar.setMaxDayCharacters(1);
        //calendar.setTodayButtonText("Hoy Día");
        //calendar.setTodayButtonVisible(true);
        calendar.setWeekOfYearVisible(false);
        this.add(calendar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Selecciones la fecha de entrega del pedido:");

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //GregorianCalendar cal = new GregorianCalendar();
        fechaSel.setTime(calendar.getDate());
        fechaSelString=FechasUtils.getFechaString(fechaSel);
        opcion=FechaEntrega.ACEPTAR;
        Window w = SwingUtilities.getWindowAncestor(this);
        w.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    public String getOpcion() {
        return opcion;
    }

    public void setOpcion(String opcion) {
        this.opcion = opcion;
    }

    public GregorianCalendar getFechaSel() {
        return fechaSel;
    }

    public String getFechaSelString() {
        return fechaSelString;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
