/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package flores.app;

import flores.Beans.ComposicionBean;
import flores.Beans.FlorBean;
import flores.gestores.GestionComposicionesBD;
import flores.gestores.GestionFloresBD;
import flores.utils.FechasUtils;
import flores.utils.Utils;
import java.awt.event.MouseAdapter;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vPalomo
 */
public class FloresMain extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public FloresMain() {
        initComponents();
        ponerListenerTablaComposiciones();
        ponerListenerTablaNuevaComposicion();
        ponerListenerTablaFlorAlmacen();
        
        
//        Utils.ocultaFilaN(jTableFamilias, 2);
//        DefaultTableModel datosTabla = (DefaultTableModel) jTableFamilias.getModel();
//        datosTabla.addRow(new Object[]{
//            "Rosa tallo",
//            "80",
//            "1"
//        });
//        System.out.println(jTableFamilias.getValueAt(0, 2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFlores = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFamilias = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableComposiones = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableFlorAlmacen = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableComposicionNueva = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNombreComposición = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 768));

        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jTableFlores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableFlores);

        jTableFamilias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Familia", "Cantidad", "Id"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableFamilias);
        if (jTableFamilias.getColumnModel().getColumnCount() > 0) {
            jTableFamilias.getColumnModel().getColumn(0).setMinWidth(80);
            jTableFamilias.getColumnModel().getColumn(0).setPreferredWidth(80);
            jTableFamilias.getColumnModel().getColumn(1).setMinWidth(80);
            jTableFamilias.getColumnModel().getColumn(1).setPreferredWidth(80);
            jTableFamilias.getColumnModel().getColumn(2).setMinWidth(20);
            jTableFamilias.getColumnModel().getColumn(2).setPreferredWidth(20);
            jTableFamilias.getColumnModel().getColumn(2).setMaxWidth(20);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(609, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Almacen", jPanel1);

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        jTableComposiones.setAutoCreateRowSorter(true);
        jTableComposiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "Fecha Alta", "Observacinoes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableComposiones.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTableComposiones);
        if (jTableComposiones.getColumnModel().getColumnCount() > 0) {
            jTableComposiones.getColumnModel().getColumn(0).setMinWidth(20);
            jTableComposiones.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTableComposiones.getColumnModel().getColumn(0).setMaxWidth(20);
        }

        jTableFlorAlmacen.setAutoCreateRowSorter(true);
        jTableFlorAlmacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Familia", "Nombre", "Color", "Almacen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableFlorAlmacen);
        if (jTableFlorAlmacen.getColumnModel().getColumnCount() > 0) {
            jTableFlorAlmacen.getColumnModel().getColumn(0).setPreferredWidth(25);
        }

        jTableComposicionNueva.setAutoCreateRowSorter(true);
        jTableComposicionNueva.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Familia", "Nombre", "Color", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTableComposicionNueva);
        if (jTableComposicionNueva.getColumnModel().getColumnCount() > 0) {
            jTableComposicionNueva.getColumnModel().getColumn(0).setMinWidth(25);
            jTableComposicionNueva.getColumnModel().getColumn(0).setPreferredWidth(25);
            jTableComposicionNueva.getColumnModel().getColumn(0).setMaxWidth(25);
        }

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Contenido de la composición");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Composiciones definidas");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Flores disponibles");

        jLabel4.setText("Nombre composición:");

        jButton1.setText("<html>Encargar<br>con cliente</html>");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<html>Encargar<br><b>sin</b> cliente");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTextFieldNombreComposición, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNombreComposición, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ramos", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        //Pestaña ramos
        cargarTablaComposiciones();
        cargarTablaAlmacen();
        
    }//GEN-LAST:event_jPanel2ComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JDialog frame = new JDialog(this, "Encargos - Elegir cliente", true);
        frame.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
        frame.getContentPane().add(new ListaClientes());
        frame.pack();
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
        //iniciarMisComponentes();
        frame.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        //Pestaña inicial
        jTableFlores.getColumnModel().getColumn(0).setCellRenderer(jTableFlores.getTableHeader().getDefaultRenderer());
    }//GEN-LAST:event_jPanel1ComponentShown

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //boton de encargo sin cliente
        //String fecha=JOptionPane.showInputDialog(this, "Fecha de entrega",FechasUtils.fechaActualString());
        JDialog frame = new JDialog(this, "fecha", true);
        frame.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
        FechaEntrega ventanaF=new FechaEntrega();
        frame.getContentPane().add(ventanaF);
        frame.pack();
        frame.setLocationRelativeTo(this);
        frame.setVisible(true);
        //iniciarMisComponentes();
        frame.setVisible(false);
        System.out.println("Fecha: "+ventanaF.getFechaSelString());
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FloresMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FloresMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FloresMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FloresMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FloresMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableComposicionNueva;
    private javax.swing.JTable jTableComposiones;
    private javax.swing.JTable jTableFamilias;
    private javax.swing.JTable jTableFlorAlmacen;
    private javax.swing.JTable jTableFlores;
    private javax.swing.JTextField jTextFieldNombreComposición;
    // End of variables declaration//GEN-END:variables

    private void cargarTablaComposiciones() {
        ArrayList<ComposicionBean> lista = GestionComposicionesBD.getListaComposiciones();
        DefaultTableModel datosTabla = (DefaultTableModel) jTableComposiones.getModel();
        for (int i = datosTabla.getRowCount(); i > 0; i--) {
            datosTabla.removeRow(i - 1);
        }
        for (ComposicionBean compo : lista) {
            datosTabla.addRow(new Object[]{
                compo.getIdComposicion(),
                compo.getNombre(),
                compo.getFechaAlta(),
                compo.getObservaciones()
            });
        }
    }
    
    private void cargarTablaAlmacen() {
        ArrayList<FlorBean> lista = GestionFloresBD.getListaFloresAlmacen();
        DefaultTableModel datosTabla = (DefaultTableModel) jTableFlorAlmacen.getModel();
        for (int i = datosTabla.getRowCount(); i > 0; i--) {
            datosTabla.removeRow(i - 1);
        }
        for (FlorBean flor : lista) {
            datosTabla.addRow(new Object[]{
                flor.getIdFlor(),
                flor.getNombreFamilia(),
                flor.getNombre(),
                flor.getColor(),
                flor.getCantidadAlmacen()
            });
        }
    }

    private void ponerListenerTablaComposiciones() {
        jTableComposiones.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {
                    System.out.println("Se ha hecho doble click - cargamos las flores del ramo");
                    String idCompo = (String) jTableComposiones.getValueAt(jTableComposiones.getSelectedRow(), 0);
                    ArrayList<FlorBean> lista = GestionComposicionesBD.getListaFloresCompo(idCompo);
                    DefaultTableModel datosTabla = (DefaultTableModel) jTableComposicionNueva.getModel();
                    for (int i = datosTabla.getRowCount(); i > 0; i--) {
                        datosTabla.removeRow(i - 1);
                    }
                    for (FlorBean flor : lista) {
                        datosTabla.addRow(new Object[]{
                            flor.getIdFlor(),
                            flor.getIdFamilia(),
                            flor.getNombre(),
                            flor.getColor(),
                            flor.getCantMinima()
                        });
                    }
                }
            }
        });
    }

    private void ponerListenerTablaNuevaComposicion() {
        jTableComposicionNueva.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {
                    System.out.println("Se ha hecho doble click - quitamos una flor");
                    String idFlor = (String) jTableComposicionNueva.getValueAt(jTableComposicionNueva.getSelectedRow(), 0);
                    int cantidad = (Integer) jTableComposicionNueva.getValueAt(jTableComposicionNueva.getSelectedRow(), 4);
                    //cantidad--;
                    if(cantidad==1){
                        ((DefaultTableModel)jTableComposicionNueva.getModel()).removeRow(jTableComposicionNueva.getSelectedRow());
                        //jTableComposicionNueva.removeRowSelectionInterval(jTableComposicionNueva.getSelectedRow(), jTableComposicionNueva.getSelectedRow());
                    }else{
                        jTableComposicionNueva.setValueAt(--cantidad, jTableComposicionNueva.getSelectedRow(), 4);
                    }

                }
            }
        });
    }

    private void ponerListenerTablaFlorAlmacen() {
        jTableFlorAlmacen.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 2) {
                    
                    String idFlor = (String) jTableFlorAlmacen.getValueAt(jTableFlorAlmacen.getSelectedRow(), 0);
                    System.out.println("Se ha hecho doble click - añadimos una flor: "+idFlor);
                    boolean existe=false;
                    for (int i=0;i< jTableComposicionNueva.getRowCount();i++){
                        String idTabla=(String) jTableComposicionNueva.getValueAt(i, 0);
                        if(idFlor.equals(idTabla)){
                            System.out.println("Sumando 1 flor. Fila "+i);
                            System.out.println(jTableComposicionNueva.getValueAt(i, 4));
                            existe=true;
                            int cantidad = (Integer)jTableComposicionNueva.getValueAt(i, 4);
                            jTableComposicionNueva.setValueAt(++cantidad, i, 4);
                        }
                    }
                    if(!existe){
                        System.out.println("Añadiendo flor");    
                        String nFamilia = (String) jTableFlorAlmacen.getValueAt(jTableFlorAlmacen.getSelectedRow(), 1);
                        String nombre = (String) jTableFlorAlmacen.getValueAt(jTableFlorAlmacen.getSelectedRow(), 2);
                        String color = (String) jTableFlorAlmacen.getValueAt(jTableFlorAlmacen.getSelectedRow(), 3);
                        ((DefaultTableModel)jTableComposicionNueva.getModel()).addRow(new Object[]{
                            idFlor,
                            nFamilia,
                            nombre,
                            color,
                            1}
                        );
                    }
                    
                }
            }
        });
    }
}
